export const FETCH_TRIPS = "FETCH_TRIPS";
export const FETCH_SINGLE_TRIP = "FETCH_SINGLE_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const CLEAR_ERRORS = "CLEAR ERRORS";
